export const DEMO_GAME_ID = "demo";

export const demoGame = {
  id: DEMO_GAME_ID,
  status: 1,
  venue: "Demo Dome",
  attendance: "24,308",
  weather: "실내 경기장",
  awayTeam: {
    code: "FCB",
    name: "Full Count Bears",
    city: "Seoul",
  },
  homeTeam: {
    code: "FCW",
    name: "Full Count Waves",
    city: "Busan",
  },
  awayHits: 8,
  awayErrors: 0,
  homeHits: 7,
  homeErrors: 1,
  awayLineup: [
    { order: 1, name: "Kim Min", position: "CF" },
    { order: 2, name: "Park Joon", position: "SS" },
    { order: 3, name: "Lee Woo", position: "RF" },
    { order: 4, name: "Choi Han", position: "1B" },
    { order: 5, name: "Jung Ho", position: "3B" },
    { order: 6, name: "Yoon Seok", position: "LF" },
    { order: 7, name: "Han Jun", position: "DH" },
    { order: 8, name: "Seo Min", position: "2B" },
    { order: 9, name: "Lim Tae", position: "C" },
  ],
  homeLineup: [
    { order: 1, name: "Ryu Chan", position: "CF" },
    { order: 2, name: "Baek Jin", position: "2B" },
    { order: 3, name: "Song Woo", position: "RF" },
    { order: 4, name: "Moon Tae", position: "DH" },
    { order: 5, name: "Ahn Gyu", position: "1B" },
    { order: 6, name: "Shin Ho", position: "3B" },
    { order: 7, name: "Ko Jun", position: "LF" },
    { order: 8, name: "Nam Hyun", position: "SS" },
    { order: 9, name: "Oh Min", position: "C" },
  ],
};

export const demoSnapshots = [
  {
    liveData: {
      awayScore: 2,
      homeScore: 1,
      currentInning: 6,
      inningHalf: "TOP",
      balls: 1,
      strikes: 2,
      outs: 1,
      base1b: true,
      base2b: false,
      base3b: false,
      currentBatter: "Lee Woo",
      currentPitcher: "Baek Jin",
      lastPitch: "직구 148km/h",
      awayInningScores: [0, 1, 0, 1, 0, 0, 0, 0, 0],
      homeInningScores: [0, 0, 1, 0, 0, 0, 0, 0, 0],
    },
    relayEvents: [
      {
        id: "demo-1",
        stamp: "6회초 1아웃",
        clock: "19:24",
        headline: "Lee Woo 좌전 안타",
        detail: "2스트라이크 이후 밀어쳐 선두타자가 출루했습니다.",
        score: { away: 2, home: 1 },
        matchup: { batter: "Lee Woo", pitcher: "Baek Jin" },
        tag: "H",
      },
      {
        id: "demo-0",
        stamp: "5회말 종료",
        clock: "19:21",
        headline: "Moon Tae 뜬공 아웃",
        detail: "중견수 정면 타구로 이닝이 종료됩니다.",
        score: { away: 2, home: 1 },
        matchup: { batter: "Moon Tae", pitcher: "Jung Ho" },
        tag: "OUT",
      },
    ],
  },
  {
    liveData: {
      awayScore: 2,
      homeScore: 3,
      currentInning: 7,
      inningHalf: "BOTTOM",
      balls: 3,
      strikes: 1,
      outs: 2,
      base1b: false,
      base2b: true,
      base3b: false,
      currentBatter: "Moon Tae",
      currentPitcher: "Jung Ho",
      lastPitch: "슬라이더 136km/h",
      awayInningScores: [0, 1, 0, 1, 0, 0, 0, 0, 0],
      homeInningScores: [0, 0, 1, 0, 0, 2, 0, 0, 0],
    },
    relayEvents: [
      {
        id: "demo-3",
        stamp: "7회말 2아웃",
        clock: "19:32",
        headline: "Moon Tae 역전 2루타",
        detail: "우중간을 가르는 장타로 주자 2명이 홈을 밟았습니다.",
        score: { away: 2, home: 3 },
        matchup: { batter: "Moon Tae", pitcher: "Jung Ho" },
        tag: "2B",
      },
      {
        id: "demo-2",
        stamp: "7회말 1아웃",
        clock: "19:29",
        headline: "Ahn Gyu 볼넷",
        detail: "풀카운트 승부 끝에 걸어 나갑니다.",
        score: { away: 2, home: 1 },
        matchup: { batter: "Ahn Gyu", pitcher: "Jung Ho" },
        tag: "BB",
      },
    ],
  },
  {
    liveData: {
      awayScore: 4,
      homeScore: 3,
      currentInning: 9,
      inningHalf: "TOP",
      balls: 0,
      strikes: 2,
      outs: 2,
      base1b: false,
      base2b: false,
      base3b: true,
      currentBatter: "Choi Han",
      currentPitcher: "Baek Jin",
      lastPitch: "포크볼 132km/h",
      awayInningScores: [0, 1, 0, 1, 0, 0, 2, 0, 0],
      homeInningScores: [0, 0, 1, 0, 0, 2, 0, 0, 0],
    },
    relayEvents: [
      {
        id: "demo-5",
        stamp: "9회초 2아웃",
        clock: "19:46",
        headline: "Choi Han 1타점 적시타",
        detail: "중전 안타로 3루 주자를 불러들였습니다.",
        score: { away: 4, home: 3 },
        matchup: { batter: "Choi Han", pitcher: "Baek Jin" },
        tag: "RBI",
      },
      {
        id: "demo-4",
        stamp: "8회초 2아웃",
        clock: "19:41",
        headline: "Park Joon 도루 성공",
        detail: "2루를 훔치며 득점권에 들어갑니다.",
        score: { away: 3, home: 3 },
        matchup: { batter: "Lee Woo", pitcher: "Baek Jin" },
        tag: "SB",
      },
    ],
  },
];

export const demoScheduleGame = {
  id: DEMO_GAME_ID,
  time: "19:00",
  stadium: demoGame.venue,
  status: "시연 중계",
  homeTeam: {
    name: demoGame.homeTeam.name,
    code: demoGame.homeTeam.code,
    score: demoSnapshots[0].liveData.homeScore,
    accent: "is-blue",
  },
  awayTeam: {
    name: demoGame.awayTeam.name,
    code: demoGame.awayTeam.code,
    score: demoSnapshots[0].liveData.awayScore,
    accent: "is-red",
  },
};
