export const liveGameMock = {
  gameId: "20260311-nyy-lad",
  venue: "Dodger Stadium",
  attendance: "48,120",
  weather: "맑음 19°C",
  broadcastStatus: "LIVE",
  matchup: {
    away: {
      city: "New York",
      name: "Yankees",
      shortName: "NYY",
      color: "#132448",
      accent: "#c4ced4",
      score: 5,
      hits: 9,
      errors: 0,
    },
    home: {
      city: "Los Angeles",
      name: "Dodgers",
      shortName: "LAD",
      color: "#005a9c",
      accent: "#ffffff",
      score: 4,
      hits: 8,
      errors: 1,
    },
  },
  inningScores: [
    { inning: 1, away: 0, home: 1 },
    { inning: 2, away: 1, home: 0 },
    { inning: 3, away: 0, home: 0 },
    { inning: 4, away: 2, home: 1 },
    { inning: 5, away: 0, home: 0 },
    { inning: 6, away: 1, home: 0 },
    { inning: 7, away: 0, home: 2 },
    { inning: 8, away: 0, home: 0 },
    { inning: 9, away: 1, home: 0 },
  ],
  summary: {
    probableMvp: "A. Judge",
    lastPitch: "95.8mph 4-Seam Fastball",
    winProbability: {
      away: 63,
      home: 37,
    },
  },
  lineup: {
    away: [
      "1. T. Grisham CF",
      "2. J. Soto RF",
      "3. A. Judge DH",
      "4. G. Stanton LF",
      "5. A. Rizzo 1B",
      "6. G. Torres 2B",
      "7. A. Volpe SS",
      "8. J. Trevino C",
      "9. O. Cabrera 3B",
    ],
    home: [
      "1. M. Betts SS",
      "2. S. Ohtani DH",
      "3. F. Freeman 1B",
      "4. T. Hernandez RF",
      "5. M. Smith C",
      "6. M. Muncy 3B",
      "7. J. Outman CF",
      "8. G. Lux 2B",
      "9. C. Taylor LF",
    ],
  },
};

export const initialRelayEvents = [
  {
    id: 1,
    stamp: "7회말 2아웃",
    clock: "21:11",
    headline: "오타니 중전 안타",
    detail: "2사 주자 없는 상황에서 오타니가 1-2 카운트 슬라이더를 받아쳐 중전 안타를 만듭니다.",
    score: { away: 4, home: 4 },
    inningState: { label: "7회말", outs: 2, balls: 0, strikes: 0 },
    bases: { first: true, second: false, third: false },
    matchup: { batter: "S. Ohtani", pitcher: "C. Holmes" },
    tag: "HIT",
  },
  {
    id: 2,
    stamp: "7회말 2아웃",
    clock: "21:14",
    headline: "프리먼 볼넷",
    detail: "바깥쪽 승부가 연속으로 빗나가며 볼넷. 1, 2루 기회가 만들어집니다.",
    score: { away: 4, home: 4 },
    inningState: { label: "7회말", outs: 2, balls: 4, strikes: 0 },
    bases: { first: true, second: true, third: false },
    matchup: { batter: "F. Freeman", pitcher: "C. Holmes" },
    tag: "BB",
  },
  {
    id: 3,
    stamp: "7회말 2아웃",
    clock: "21:17",
    headline: "테오스카 2타점 2루타",
    detail: "우중간 깊숙한 장타. 주자 둘 모두 홈을 밟으면서 다저스가 6-4로 앞서갑니다.",
    score: { away: 4, home: 6 },
    inningState: { label: "7회말", outs: 2, balls: 0, strikes: 1 },
    bases: { first: false, second: true, third: false },
    matchup: { batter: "T. Hernandez", pitcher: "C. Holmes" },
    tag: "2 RBI",
  },
  {
    id: 4,
    stamp: "7회말 종료",
    clock: "21:20",
    headline: "맥스 먼시 헛스윙 삼진",
    detail: "낮은 스위퍼에 방망이가 헛돌며 이닝 종료. 다저스가 6-4 리드를 지킵니다.",
    score: { away: 4, home: 6 },
    inningState: { label: "이닝 종료", outs: 3, balls: 0, strikes: 3 },
    bases: { first: false, second: false, third: false },
    matchup: { batter: "M. Muncy", pitcher: "C. Holmes" },
    tag: "K",
  },
];

export const incomingRelayQueue = [
  {
    id: 5,
    stamp: "8회초 1아웃",
    clock: "21:28",
    headline: "저지 솔로 홈런",
    detail: "높게 들어온 체인지업을 걷어 올려 좌측 담장을 넘깁니다. 양키스가 한 점 차로 추격합니다.",
    score: { away: 5, home: 6 },
    inningState: { label: "8회초", outs: 1, balls: 0, strikes: 0 },
    bases: { first: false, second: false, third: false },
    matchup: { batter: "A. Judge", pitcher: "E. Phillips" },
    tag: "HR",
  },
  {
    id: 6,
    stamp: "8회초 종료",
    clock: "21:34",
    headline: "스탠튼 병살타",
    detail: "낮은 싱커를 건드린 타구가 유격수 정면으로 향하며 병살 처리됩니다.",
    score: { away: 5, home: 6 },
    inningState: { label: "공수교대", outs: 3, balls: 0, strikes: 1 },
    bases: { first: false, second: false, third: false },
    matchup: { batter: "G. Stanton", pitcher: "E. Phillips" },
    tag: "DP",
  },
  {
    id: 7,
    stamp: "9회말 전",
    clock: "21:42",
    headline: "클로저 예고",
    detail: "양키스는 9회말 수비를 앞두고 마무리 투수 C. Holmes를 재투입할 준비를 합니다.",
    score: { away: 5, home: 6 },
    inningState: { label: "8회말 종료", outs: 3, balls: 0, strikes: 0 },
    bases: { first: false, second: false, third: false },
    matchup: { batter: "-", pitcher: "C. Holmes" },
    tag: "NOTE",
  },
  {
    id: 8,
    stamp: "9회초 2아웃",
    clock: "21:51",
    headline: "리조 적시 2루타",
    detail: "2사 1루에서 좌중간을 가르는 적시 2루타. 경기가 6-6 동점이 됩니다.",
    score: { away: 6, home: 6 },
    inningState: { label: "9회초", outs: 2, balls: 1, strikes: 2 },
    bases: { first: false, second: true, third: false },
    matchup: { batter: "A. Rizzo", pitcher: "B. Treinen" },
    tag: "RBI",
  },
];

export const initialChatMessages = [
  {
    id: 1,
    author: "핀스트라이프",
    team: "away",
    text: "저지 타석 들어오면 분위기 바로 바뀔 듯",
    time: "21:12",
  },
  {
    id: 2,
    author: "블루다저",
    team: "home",
    text: "7회말 집중력 좋다. 테오스카 오늘 해결사네",
    time: "21:18",
  },
  {
    id: 3,
    author: "볼카운터",
    team: "neutral",
    text: "카운트랑 주자 현황이 커서 보기 편하다",
    time: "21:19",
  },
];

export const incomingChatQueue = [
  {
    id: 4,
    author: "클러치히어로",
    team: "away",
    text: "저지 홈런이면 바로 다시 붙는다",
    time: "21:27",
  },
  {
    id: 5,
    author: "웨스트코스트",
    team: "home",
    text: "필립스 오늘 구위 괜찮은데 장타 조심",
    time: "21:30",
  },
  {
    id: 6,
    author: "스탯중계봇",
    team: "neutral",
    text: "현재 다저스 승리 확률 58.4%",
    time: "21:33",
  },
  {
    id: 7,
    author: "핀스트라이프",
    team: "away",
    text: "리조가 한 방 쳐주면 연장 간다",
    time: "21:47",
  },
];
